### ISSUE TITLE
Smooth transition between zoom levels 

### ISSUE THREAD

**Issue by AmandaWetter** [camptocamp/GeoMapFish#92]
### Who requested this new feature?
>  Amanda Wetter, Kanton Schwyz, Amt für Geoinformation

### Is your feature request related to a problem?
> Yes
> When quickly zooming into the map (especially with the mouse), the map appears to re-center itself. This results in a sudden movement along the X and Y axes. Due to the re-centering, the point you want to zoom in on shifts.

### Describe the solution you'd like
> The abrupt re-centering should be minimized. The point you want to zoom in on should not shift.

### Additional information or points to watch out for
> 
>

**Comment by ger-benjamin** [comment]
Hi @AmandaWetter ,

I've found the issue and have open a PR in your repository. Could you please test it ?

The issue looks coming from the `vars.yaml` in `<interface>/constants/gmfOptions/view` the `constrainResolution` variable is now set to `true` by default (you can modify it, or/and check your `update_paths`). Which in my own opinion should be not the case. We can see that the zoom is done, and then Openlayers constraint the resolution to the defined value, which produce this little "jump".
And that's why we have it on the GMF demo `desktop` interface, but not on the `desktop_alt` one.

**Comment by maltaesousa** [comment]
Hi @ger-benjamin 
Thanks for your help. We are also interested in this issue at SITN because we use `constrainResolution` and we need them.

It looks like this option hides the problem but it's not the cause of it. We have an example of plain OpenLayers here with constrained resolutions that does not behave the same:

https://sitn.ne.ch/services/docs/examples/wmts-plain

Here's a video showing the above example and then the same on GMF with the map glitching:


https://github.com/user-attachments/assets/9caab0c3-5a15-4438-a132-78e6ffae3062

**Comment by ger-benjamin** [comment]
Thanks for your contribution @maltaesousa ,
That allowed me to understand deeper the issue.

I'm (nearly) sure now that the real issue come from https://github.com/camptocamp/ngeo/blob/2.9/src/controllers/AbstractAppController.js#L134-L136

I'll find a way to fix it.

**Comment by ger-benjamin** [comment]
This will fix this issue https://github.com/camptocamp/ngeo/pull/9541 :-)
